root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd"
entrypoint = "./tmp/main"
delay = 500
exclude_dir = ["tmp", "vendor"]
include_ext = ["go"]
exclude_file = ["*.md"]

[log]
time = true

[env]
APP_ENV = "development"